mybatis:
  type-aliases-package: com.zzu.diting.entity
  mapper-locations: classpath:com/zzu/diting/mapper/*Mapper.xml

spring:
  application:
    name: diting-online-core
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    password: jcy123456
    username: root
    url: jdbc:mysql://localhost:3306/ditingtest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver




