mybatis:
  type-aliases-package: com.zzu.diting.entity
  mapper-locations: classpath:com/zzu/diting/mapper/*Mapper.xml

spring:
  application:
    name: diting-online-core
  mvc:
    view:
      prefix: /
      suffix: .jsp



