spring:
  application:
    name: diting-online
  mvc:
    view:
      suffix: /
      prefix: .jsp
  http:
    converters:
      preferred-json-mapper: jackson
  servlet:
    multipart:
      maxFileSize: 30MB
      max-request-size: 100MB
server:
  servlet:
    context-path: /diting-online
    jsp:
      init-parameters:
        development: true
  port: 8083